# Cấu hình bộ điều khiển ROS2 cho robot
# use_sim_time = true: nếu chạy trong Gazebo mô phỏng thì phải bật.
# Nếu chạy trên robot thật thì để false hoặc không thiết lập.
controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    # Sử dụng thời gian mô phỏng
    use_sim_time: true
    publish_rate: 50.0
    base_frame_id: base_link

    # Nếu true, bộ điều khiển sẽ phát transform giữa odom và base_link.
    enable_odom_tf: true

    # Nếu dùng velocity stamped, đổi thành true.
    use_stamped_vel: false

    # Tên các joint của bánh xe trái/phải trong URDF
    left_wheel_names: ['Banh_trai_joint']
    right_wheel_names: ['Banh_phai_joint']
    wheel_separation: 0.23
    wheel_radius: 0.0325

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.4
        has_acceleration_limits: true
        max_acceleration       : 0.5
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.5
        has_acceleration_limits: true
        max_acceleration       : 1.0