controller_manager:
  ros__parameters:
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    
    # ÉP PHÁT ODOM CHO SLAM
    odom_frame_id: odom
    enable_odom_tf: true
    
    use_stamped_vel: false
    left_wheel_names: ['Banh_trai_joint']
    right_wheel_names: ['Banh_phai_joint']
    wheel_separation: 0.23
    wheel_radius: 0.0325

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0
        has_acceleration_limits: true
        max_acceleration       : 0.5
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.5
        has_acceleration_limits: true
        max_acceleration       : 1.0